-- liquibase formatted sql
-- Format: --changeset author:id attribute1:value1 attribute2:value2 [...]

-- changeset VaolEr:Create_Users_table
CREATE TABLE Users
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    firstname           VARCHAR(64) NOT NULL,
    lastname            VARCHAR(64) NOT NULL,
    login               VARCHAR(255) NOT NULL,
    password            VARCHAR(255) NOT NULL
);

-- changeset VaolEr:Create_Events_table
CREATE TABLE Events
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                VARCHAR(64) NOT NULL,
    description         VARCHAR(255),
    creatorUser_id      integer NOT NULL
);

-- changeset VaolEr:Create_MeetingRooms_table
CREATE TABLE MeetingRooms
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name                VARCHAR(64) NOT NULL
);

-- changeset VaolEr:Create_Events_Dates_table
CREATE TABLE Events_Dates
(
    id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    date                date NOT NULL,
    event_id            integer NOT NULL,
    startTime           timestamp NOT NULL,
    endTime             timestamp NOT NULL,
    meetingRoom_id      integer NOT NULL
);

-- changeset VaolEr:Alter_Events_table_fks
ALTER TABLE Events
    ADD CONSTRAINT Events_fk0 FOREIGN KEY (creatorUser_id) REFERENCES Users (id);

-- changeset VaolEr:Alter_Events_ScheduleDates_table_fks
ALTER TABLE Events_Dates
    ADD CONSTRAINT Events_ScheduleDates_fk0 FOREIGN KEY (event_id) REFERENCES Events (id);
ALTER TABLE Events_Dates
    ADD CONSTRAINT Events_ScheduleDates_fk1 FOREIGN KEY (meetingRoom_id) REFERENCES MeetingRooms (id);
